// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as React$1 from "@remix-run/react";

ReactDom.hydrate(React.createElement(React$1.RemixBrowser, {}), document);

export {
  
}
/*  Not a pure module */
