// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nav from "./components/Nav.js";
import * as React from "react";
import * as React$1 from "@remix-run/react";

function meta(param) {
  return {
          title: "rescript remix blog example"
        };
}

function links(param) {
  var styles = (require('./styles/global.css'));
  return [{
            rel: "stylesheet",
            href: styles
          }];
}

function Root$default(Props) {
  return React.createElement("html", {
              className: "dark",
              lang: "ko"
            }, React.createElement("head", undefined, React.createElement("meta", {
                      charSet: "utf-8"
                    }), React.createElement("meta", {
                      content: "width=device-width,initial-scale=1",
                      name: "viewport"
                    }), React.createElement(React$1.Meta, {}), React.createElement(React$1.Links, {})), React.createElement("body", {
                  className: "bg-neutral-900"
                }, React.createElement(Nav.make, {}), React.createElement(React$1.Outlet, {}), React.createElement(React$1.ScrollRestoration, {}), React.createElement(React$1.Scripts, {}), React.createElement(React$1.LiveReload, {})));
}

var $$default = Root$default;

export {
  meta ,
  links ,
  $$default ,
  $$default as default,
  
}
/* Nav Not a pure module */
