// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Index$Header(Props) {
  return React.createElement(React.Fragment, undefined, "BLOG NAME");
}

var Header = {
  make: Index$Header
};

function Index$default(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Index$Header, {}));
}

var $$default = Index$default;

export {
  Header ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
