// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AMdx from "./posts/a.mdx";
import * as BMdx from "./posts/b.mdx";
import * as $$Node from "@remix-run/node";
import * as React$1 from "@remix-run/react";

var attr = AMdx.attributes;

var name = AMdx.filename;

var PostA = {
  attr: attr,
  name: name
};

var attr$1 = BMdx.attributes;

var name$1 = BMdx.filename;

var PostB = {
  attr: attr$1,
  name: name$1
};

function makeSlug(name) {
  return name.replace(".mdx", "");
}

function loader(param) {
  return $$Node.json([
              {
                attr: attr,
                slug: name.replace(".mdx", "")
              },
              {
                attr: attr$1,
                slug: name$1.replace(".mdx", "")
              }
            ]);
}

function Index$Post(Props) {
  var title = Props.title;
  var des = Props.des;
  var date = Props.date;
  var image = Props.image;
  var slug = Props.slug;
  return React.createElement(React$1.Link, {
              prefetch: "intent",
              to: "/posts/" + slug,
              children: null,
              className: "max-w-3xl w-full p-5 rounded-lg bg-neutral-800 my-3 flex flex-nowrap items-center justify-between cursor-pointer transition duration-500 ease-in-out border border-solid border-black hover:border-green-200"
            }, React.createElement("div", {
                  className: "flex flex-col flex-1 mr-2"
                }, React.createElement("div", {
                      className: "text-white text-2xl font-bold"
                    }, title), React.createElement("div", {
                      className: "text-neutral-300 text-base font-extralight pb-2"
                    }, des), React.createElement("div", {
                      className: "text-neutral-600 text-xs font-medium"
                    }, date)), React.createElement("img", {
                  className: "rounded w-24 h-24 object-cover",
                  src: image
                }));
}

var Post = {
  make: Index$Post
};

function Index$default(Props) {
  var posts = React$1.useLoaderData();
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "w-full flex py-5"
                }, React.createElement("div", {
                      className: "text-green-500 text-[15vw] font-black  m-auto"
                    }, "Res + Remix")), React.createElement("div", {
                  className: "w-full flex flex-col items-center px-5 mb-5"
                }, posts.map(function (post) {
                      return React.createElement(Index$Post, {
                                  title: post.attr.meta.title,
                                  des: post.attr.meta.description,
                                  date: post.attr.meta.date,
                                  image: post.attr.meta.thumbnail,
                                  slug: post.slug,
                                  key: post.slug
                                });
                    })));
}

var $$default = Index$default;

export {
  PostA ,
  PostB ,
  makeSlug ,
  loader ,
  Post ,
  $$default ,
  $$default as default,
  
}
/* attr Not a pure module */
