// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as React$1 from "@remix-run/react";

function $$default(param) {
  return React.createElement("div", {
              className: "w-full py-7 flex flex-col items-center"
            }, React.createElement("div", {
                  className: "max-w-5xl w-full prose dark:prose-invert px-10"
                }, React.createElement(React$1.Outlet, {})));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
