// Generated by ReScript, PLEASE EDIT WITH CARE


var Meta = {};

var Links = {};

var Outlet = {};

var ScrollRestoration = {};

var Scripts = {};

var LiveReload = {};

var RemixBrowser = {};

export {
  Meta ,
  Links ,
  Outlet ,
  ScrollRestoration ,
  Scripts ,
  LiveReload ,
  RemixBrowser ,
  
}
/* No side effect */
